In [1]:
import numpy as np

import pandas as pd

import seaborn as sns

import matplotlib.pyplot as plt

In [6]:
data = data = pd.read_csv('C:/Users/iop03/OneDrive/바탕 화면/갸울 방학 공부/ai/Applications_of_DL-main/dataset.csv')

In [8]:
data.keys()

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [11]:
data_input = data[['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal']].to_numpy()

In [12]:
data_target = data['target'].to_numpy()

In [13]:
from sklearn.model_selection import train_test_split
train_input,test_input, train_target, test_target = train_test_split(data_input, data_target, random_state=0)

In [14]:
from sklearn.preprocessing import StandardScaler

# StandardScaler 객체 생성
ss = StandardScaler()

# 훈련 데이터에 맞춰 스케일 조정
ss.fit(train_input)

# 훈련 데이터와 테스트 데이터에 스케일 조정 적용
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

In [15]:
# SVM

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC

clf_svm = SVC(random_state=0)
clf_svm.fit(train_input, train_target)

pred_svm = clf_svm.predict(test_input)

print("\n--- SVM Classifier ---")
print(accuracy_score(test_target, pred_svm))
print(confusion_matrix(test_target, pred_svm))


--- SVM Classifier ---
0.6842105263157895
[[15 18]
 [ 6 37]]


In [16]:
# LR

from sklearn.linear_model import LogisticRegression

clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(train_input, train_target)

pred_lr = clf_lr.predict(test_input)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(test_target, pred_lr))
print (confusion_matrix(test_target, pred_lr))


--- Logistic Regression Classifier ---
0.8421052631578947
[[24  9]
 [ 3 40]]


C:\Users\iop03\anaconda3\envs\aistudy\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [17]:
# DT

from sklearn.tree import DecisionTreeClassifier

clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(train_input, train_target)

pred_dt = clf_dt.predict(test_input)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(test_target, pred_dt))
print (confusion_matrix(test_target, pred_dt))


--- Decision Tree Classifier ---
0.7894736842105263
[[24  9]
 [ 7 36]]


In [18]:
# RT

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd

print ("\n--- Random Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(train_input, train_target)
pred = rf_clf.predict(test_input)
print(accuracy_score(test_target,pred))
print (confusion_matrix(test_target, pred))


--- Random Forest ---
0.868421052631579
[[26  7]
 [ 3 40]]
