In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
df = pd.read_csv('C:/Users/iop03/OneDrive/바탕 화면/갸울 방학 공부/ai/data/abalone.csv')
df

Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
0      M   0.455     0.365   0.095        0.5140          0.2245   
1      M   0.350     0.265   0.090        0.2255          0.0995   
2      F   0.530     0.420   0.135        0.6770          0.2565   
3      M   0.440     0.365   0.125        0.5160          0.2155   
4      I   0.330     0.255   0.080        0.2050          0.0895   
...   ..     ...       ...     ...           ...             ...   
4172   F   0.565     0.450   0.165        0.8870          0.3700   
4173   M   0.590     0.440   0.135        0.9660          0.4390   
4174   M   0.600     0.475   0.205        1.1760          0.5255   
4175   F   0.625     0.485   0.150        1.0945          0.5310   
4176   M   0.710     0.555   0.195        1.9485          0.9455   

      Viscera weight  Shell weight  Rings  
0             0.1010        0.1500     15  
1             0.0485        0.0700      7  
2             0.1415        0.2100      9  
3             0.1140        0.1550     10  
4             0.0395        0.0550      7  
...              ...           ...    ...  
4172          0.2390        0.2490     11  
4173          0.2145        0.2605     10  
4174          0.2875        0.3080      9  
4175          0.2610        0.2960     10  
4176          0.3765        0.4950     12  

[4177 rows x 9 columns]

In [8]:
from sklearn.preprocessing import LabelEncoder

label = LabelEncoder()
df['Sex'] = label.fit_transform(df['Sex'])
df.head()

Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
0    2   0.455     0.365   0.095        0.5140          0.2245   
1    2   0.350     0.265   0.090        0.2255          0.0995   
2    0   0.530     0.420   0.135        0.6770          0.2565   
3    2   0.440     0.365   0.125        0.5160          0.2155   
4    1   0.330     0.255   0.080        0.2050          0.0895   

   Viscera weight  Shell weight  Rings  
0          0.1010         0.150     15  
1          0.0485         0.070      7  
2          0.1415         0.210      9  
3          0.1140         0.155     10  
4          0.0395         0.055      7

In [9]:
y = df['Rings']
y

0       15
1        7
2        9
3       10
4        7
        ..
4172    11
4173    10
4174     9
4175    10
4176    12
Name: Rings, Length: 4177, dtype: int64

In [10]:
x = df.drop('Rings', axis=1)
x

Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
0       2   0.455     0.365   0.095        0.5140          0.2245   
1       2   0.350     0.265   0.090        0.2255          0.0995   
2       0   0.530     0.420   0.135        0.6770          0.2565   
3       2   0.440     0.365   0.125        0.5160          0.2155   
4       1   0.330     0.255   0.080        0.2050          0.0895   
...   ...     ...       ...     ...           ...             ...   
4172    0   0.565     0.450   0.165        0.8870          0.3700   
4173    2   0.590     0.440   0.135        0.9660          0.4390   
4174    2   0.600     0.475   0.205        1.1760          0.5255   
4175    0   0.625     0.485   0.150        1.0945          0.5310   
4176    2   0.710     0.555   0.195        1.9485          0.9455   

      Viscera weight  Shell weight  
0             0.1010        0.1500  
1             0.0485        0.0700  
2             0.1415        0.2100  
3             0.1140        0.1550  
4             0.0395        0.0550  
...              ...           ...  
4172          0.2390        0.2490  
4173          0.2145        0.2605  
4174          0.2875        0.3080  
4175          0.2610        0.2960  
4176          0.3765        0.4950  

[4177 rows x 8 columns]

In [11]:
# train & test

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0)

x_train.shape, x_test.shape, y_train.shape, y_test.shape

((3132, 8), (1045, 8), (3132,), (1045,))

In [12]:
# SVM

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC

clf_svm = SVC(random_state=0)
clf_svm.fit(x_train, y_train)

pred_svm = clf_svm.predict(x_test)

print("\n--- SVM Classifier ---")
print(accuracy_score(y_test, pred_svm))
print(confusion_matrix(y_test, pred_svm))


--- SVM Classifier ---
0.24784688995215312
[[ 0  4  0  1  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  2  0 11  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  2  0 28  4  0  6  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0 29 19  5  9  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 26 30 21 35  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  5 10 56 59  8  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  5 30 82 32  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  2 15 64 40 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  2 14 42 42 20  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  2  4 38 36 13  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  2 19 16 13  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  3 15 10  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  2  6 13  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1 

In [13]:
# LR

from sklearn.linear_model import LogisticRegression

clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(x_train, y_train)

pred_lr = clf_lr.predict(x_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))


--- Logistic Regression Classifier ---
0.24784688995215312
[[ 0  0  0  7  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1 12  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 31  7  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 19 30  9  4  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 10 41 41 20  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  4 14 52 59  9  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  8 20 85 35  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1 11 17 49 39 22  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  7 16 35 41 22  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  2  9 28 37 16  0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  2  7  7 20 14  0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  4 11 13  3  0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  6 11  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0

C:\Users\iop03\anaconda3\envs\aistudy\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [14]:
# DT

from sklearn.tree import DecisionTreeClassifier

clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(x_train, y_train)

pred_dt = clf_dt.predict(x_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
0.18181818181818182
[[ 1  5  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  4  5  2  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 11  6 11  7  4  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  2  7 12 23 10  2  2  1  2  1  0  0  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  3 16 37 33 14  3  4  3  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2 10 25 30 37 14 11  3  4  1  2  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  4 11 28 41 30 13  7  7  1  4  4  2  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  8 14 34 24 19 15 11  3  4  4  1  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  2  3 10 21 35 15  9 11  3  1  1  5  5  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  2  9 20 19 11  9  9  3  3  0  0  1  2  1  0  2  2  0  0  0]
 [ 0  0  0  0  1  5  4  9  9  6  6  2  1  2  1  1  2  1  0  0  1  0  0  0]
 [ 0  0  0  0  0  2  3  2  6  5  5  2  1  2  1  0  0  3  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  6  3  2  1  1  4  0  2  1

In [15]:
# RT

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd

print ("\n--- Random Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(x_train, y_train)
pred = rf_clf.predict(x_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))


--- Random Forest ---
0.22679425837320574
[[ 0  6  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  5  5  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 10 13 12  4  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  8 19 21 10  1  2  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  3 29 31 37  7  5  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  3  6 19 52 39 15  3  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  2  8 34 42 43 16  4  1  1  0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  3  5 11 37 40 29  6  5  0  0  3  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  4  8 34 40 22  2  7  3  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  3  4 21 36 14  5  5  1  0  1  0  0  1  0  0  0  1  0  1  0]
 [ 0  0  0  0  1  4  9 10 14  5  3  1  0  0  2  1  0  1  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  5 11  8  1  0  3  2  1  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  3  4  7  3  2  2  0  0  1  0  0  0  